#driver_config:
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      network:
      - ["forwarded_port", {guest: 80, host: 8888}]

 #driver_plugin: ec2
 # driver_config:
 #   image_id: <%= ENV['AMI_ID'] %>
 #   username: ec2-user
 #   ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

suites:
  - name: default
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app-checkout]
    attributes:
