driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      network:
      - ["forwarded_port", {host: 8880, guest: 80}]
      - ["forwarded_port", {host: 8443, guest: 443}]
      - ["private_network", {ip: "10.10.10.40"}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app-checkout]
    attributes:
