# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # Install this exact version of chef-client
  require_chef_omnibus: 12.7.2


platforms:
  - name: ubuntu14
    driver:
      box: 'opscode-ubuntu-12.04'
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ['private_network', {ip: '192.168.56.40'}]

suites:
  - name: mysuite
    data_bags_path: 'test/integration/data_bags'
    run_list:
#      - recipe[myapache-cookbook::default]
#      - recipe[myapache-cookbook::app_checkout]
#      - recipe[myapache-cookbook::ssl]
#      - recipe[myapache-cookbook::audit_tests]
      - recipe[myapache-cookbook::troubleshooting]
#      - recipe[myapache-cookbook::audit_tests_dev]
#      - recipe[myapache-cookbook::sandbox]
    attributes:
      myapache-cookbook:
      data_bag:
        name: secure
        item: ssl_opschef_tv
        secret: superSECRETencryptionKEY
      artifactory_username: ENV['ARTIFACTORY_USERNAME']
      artifactory_password: ENV['ARTIFACTORY_PASSWORD']
