driver:
  name: vagrant

provisioner:
  name: chef_zero
  # Download latest stable chef-client using the install.sh script
  # require_chef_omnibus: true

  # Use the local chef-client rpm specified in install_chef_rpm.sh: 
  chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh

platforms:
  - name: centos6
    driver:
      box: centos66
      box_url: file:///Users/apop/chef-images/centos6-6.box
      network:
      - ["private_network", {ip: "192.168.56.40"}]
      synced_folders:
      - ["/Users/apop/chef-kits", "/mnt/share", "disabled: false"]
      customize:
        cpus: 1
        memory: 1024

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app-checkout]
    attributes:
