# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  vm_hostname: myapache
  customize:
    cpus: 1
    memory: 1024

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  log_level: info
  # Install this exact version of chef-client
  require_chef_omnibus: 12.18.31
  client_rb:
    data_collector.server_url: "https://ap-ca6.opschef.tv/data-collector/v0/"
    data_collector.token: '93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506'
    ssl_verify_mode: :verify_none
    verify_api_cert: false

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos6
    driver:
      box: 'centos-6.6'
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      # Use host-only network, makes life easier from a networking perspective:
      network:
      - ['private_network', {ip: '192.168.56.40'}]

suites:
  - name: mysuite2
    data_bags_path: 'test/integration/data_bags'
    run_list:
#      - recipe[myapache-cookbook::default]
      - recipe[audit::default]
    verifier:
      inspec_tests:
        - path: test/integration/mysuite/default_spec.rb
        - name: ssh-baseline
          url: https://github.com/dev-sec/ssh-baseline/archive/master.zip
        - name: os-hardening
          git: https://github.com/dev-sec/tests-os-hardening.git
    attributes:
      myapache-cookbook:
        git-repo: https://github.com/alexpop/myhtml-app
        git-revision: release-1
        doc-root: /var/www/html
      audit:
        collector: 'chef-visibility'
#        inspec_version: 1.5.0
        insecure: true
        profiles:
          - name: tmp_compliance_profile
            url: https://github.com/nathenharvey/tmp_compliance_profile
#          - name: linux-baseline
#            url: https://github.com/dev-sec/linux-baseline/archive/master.zip
#          - name: ssh-baseline
#            url: https://github.com/dev-sec/ssh-baseline/archive/master.zip
