# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  #gui: true
  # Mount local /Users/apop/chef-kits folder as /mnt/share on the VM
  synced_folders:
  - ['~/chef-kits', '/mnt/share', 'disabled: false']
  customize:
    cpus: 1
    memory: 1024

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  # Install this exact version of chef-client
  require_chef_omnibus: 12.5.1
  # Use the local chef-client rpm specified in install_chef.sh:
#  chef_omnibus_url: http://192.168.56.1/kits/install_chef_rpm.sh
  chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :enabled

platforms:
  - name: centos6
    driver:
      box: 'chef/centos-6.6'
      #box: 'chef/centos-7.1'
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ['private_network', {ip: '192.168.56.40'}]

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app_checkout]
#      - recipe[myapache-cookbook::ssl]
      - recipe[myapache-cookbook::audit_tests]
      - recipe[myapache-cookbook::troubleshooting]
#      - recipe[myapache-cookbook::audit_tests_dev]
#      - recipe[myapache-cookbook::sandbox]
    attributes:
      myapache-cookbook:
        ap_path: /mnt/share/gems/awesome_print-1.6.1.gem
        git-repo: https://github.com/alexpop/myhtml-app
        git-revision: release-1
        doc-root: /var/www/html
      data_bag:
        name: secure
        item: ssl_opschef_tv
        secret: superSECRETencryptionKEY
