driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: file:///kits/install_chef_rpm.sh

platforms:
  - name: centos6
    driver:
      box: centos66
      network:
      - ["forwarded_port", {host: 8880, guest: 80}]
      - ["private_network", {ip: "10.10.10.40"}]
      synced_folders:
      - ["/Users/apop/chef-kits", "/kits", "disabled: false"]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app-checkout]
    attributes:
