driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      network:
      - ["forwarded_port", {guest: 80, host: 8888}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[myapache-cookbook::default]
      - recipe[myapache-cookbook::app-checkout]
    attributes:
